<?php

namespace common\components;

use Yii;
require_once (Yii::getAlias("@common")."/components/phpexcel/PHPExcel.php");

/**
 * 继承原来的类，只是重载了几个函数。
 *
 */
class ExcelPreview extends \PHPExcel_Writer_HTML
{
    public static $webTile = '';

    public static function PreviewExcel($path,$format)
    {
        self::$webTile = substr(strrchr($path,'/'),1);//网页的标题
        //$filePath ='../uploads/projects/812/12345.xls';
        $filePath ='../'.$path;
        if($format == 'xlsx')//版本，是新的(xlsx)还是老的（xls）
            $objReader =new \PHPExcel_Reader_Excel2007();
        else
            $objReader =new \PHPExcel_Reader_Excel5();
        /*输出显示*/
        $objWriteHtml=new self($objReader->load($filePath));
        $objWriteHtml->writeAllSheets();//显示所有页
        $objWriteHtml->setUseInlineCss(true);//内联样式
        $objWriteHtml->generateStyles(true);

        $objWriteHtml->save("php://output");
    }

    /**
     * 生成HTML的头标签
     *
     */
    public function generateHTMLHeader($pIncludeStyles = false) {
        // PHPExcel object known?
        if (is_null($this->_phpExcel)) {
            throw new PHPExcel_Writer_Exception('Internal PHPExcel object not set to an instance of an object.');
        }

        // Construct HTML
        $properties = $this->_phpExcel->getProperties();
        $html = '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">' . PHP_EOL;
        $html .= '<!-- Generated by PHPExcel - http://www.phpexcel.net -->' . PHP_EOL;
        $html .= '<html>' . PHP_EOL;
        $html .= '  <head>' . PHP_EOL;
        $html .= '	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">' . PHP_EOL;
        if ($properties->getTitle() > '')
            $html .= '	  <title>' . htmlspecialchars($properties->getTitle()) . '</title>' . PHP_EOL;
        else
            $html .= '	  <title>' . self::$webTile . '</title>' . PHP_EOL;


        if ($properties->getCreator() > '')
            $html .= '	  <meta name="author" content="' . htmlspecialchars($properties->getCreator()) . '" />' . PHP_EOL;
        if ($properties->getTitle() > '')
            $html .= '	  <meta name="title" content="' . htmlspecialchars($properties->getTitle()) . '" />' . PHP_EOL;
        if ($properties->getDescription() > '')
            $html .= '	  <meta name="description" content="' . htmlspecialchars($properties->getDescription()) . '" />' . PHP_EOL;
        if ($properties->getSubject() > '')
            $html .= '	  <meta name="subject" content="' . htmlspecialchars($properties->getSubject()) . '" />' . PHP_EOL;
        if ($properties->getKeywords() > '')
            $html .= '	  <meta name="keywords" content="' . htmlspecialchars($properties->getKeywords()) . '" />' . PHP_EOL;
        if ($properties->getCategory() > '')
            $html .= '	  <meta name="category" content="' . htmlspecialchars($properties->getCategory()) . '" />' . PHP_EOL;
        if ($properties->getCompany() > '')
            $html .= '	  <meta name="company" content="' . htmlspecialchars($properties->getCompany()) . '" />' . PHP_EOL;
        if ($properties->getManager() > '')
            $html .= '	  <meta name="manager" content="' . htmlspecialchars($properties->getManager()) . '" />' . PHP_EOL;

        if ($pIncludeStyles) {
            $html .= $this->generateStyles(true);
        }
        /*《《《自己加的css样式*/
        $sheets = $this->_phpExcel->getAllSheets();
        $strSheentCss = $strSheentCssHover = '';
        foreach ($sheets as $sheet)
        {
            $strSheentCss .='.sheet'.$sheet->getParent()->getIndex($sheet).',';
            $strSheentCssHover .='.sheet'.$sheet->getParent()->getIndex($sheet).':hover,';
        }
        $strSheentCss = substr($strSheentCss, 0, -1);
        $strSheentCssHover = substr($strSheentCssHover, 0, -1);
        $html .= '<style>   
    ul{
        list-style: none;
    }
    
    a{
        text-decoration:none; 
    }
    
    .navigation { /*position: fixed;
                    margin-bottom: 0;*/
                    background-color: #c7d9ed;
                    width: 100%;
                    border-top: 1px solid #728ead;
                    border-left: none;
                    border-right: none;
                    border-bottom: 2px solid #849dbd;
                    height: 38px; font-size: 13.5px;
                    -webkit-user-select: none;
                    -moz-user-select: none;
                    -ms-user-select: none;
                    user-select: none; overflow: hidden;
                    position: fixed; bottom: -14px;
    }'.PHP_EOL.$strSheentCss.'{ float: left;
                padding: 1px 12px;
                border-left: 1px solid #ffffff;
                border-right: 1px solid #3c5478;
                cursor: default; color: #1e2b3e;
                height: 32px;
                line-height: 30px;
                margin-top: 1px;
                margin-bottom: 1px;
                border-radius: 0 6px 0 0;
    }'.PHP_EOL.$strSheentCssHover.'{ background-color: #dbe7f3; 
                /*border:1px solid #ffffff;*/ 
                border-left: 1px solid #ffffff; 
                border-right: 1px solid #ffffff; 
    }
    table{
        display:none;
    }
    #sheet0{
        display:block;
    }
    .sheet0{
        background-color: #eeeeee;
    }
          
</style>';
        /*自己加的css样式》》》*/

        /*《《《自己加的js事件*/
        $html .= '<script type="text/javascript">
    window.onload=function(){
        var oli = document.getElementsByTagName("li");
        var oTableNone = document.getElementsByTagName("table");
        for(var i=0;i<oli.length;i++)
        { 
            oli[i].index = i;
            oli[i].onclick = function() {
                //隐藏所有
                for(var j=0;j<i;j++)
                {
                    oTableNone[j].style.display = "none";           
                    oli[j].style.backgroundColor = "#c7d9ed";           
                }
                
                //让点击的显示
                var strTableId = "sheet"+this.index;
                var otable = document.getElementById(strTableId); 
                otable.style.display = "block";
                this.style.backgroundColor = "#eeeeee";
            }
        }
    };
    
</script>';
        /*自己加的js事件》》》*/
        $html .= '  </head>' . PHP_EOL;
        $html .= '' . PHP_EOL;
        $html .= '  <body>' . PHP_EOL;

        // Return
        return $html;
    }

    /**
     * 生成HTML的尾标签
     */
    public function generateHTMLFooter() {
        // Construct HTML
        $html = '<br/><br/><br/>';//多加几个换行，要不标签页的按钮会盖住一部分！
        //////////
        $html .= '  </body>' . PHP_EOL;
        $html .= '</html>' . PHP_EOL;

        // Return
        return $html;
    }

}

